#!/usr/bin/env bash

sudo pacman -R iptables

sudo pacman -S --noconfirm --needed \
  1password-beta \
  1password-cli \
  avahi \
  bat \
  bluetui \
  bridge-utils \
  brightnessctl \
  btop \
  clang \
  dbeaver \
  dmidecode \
  dnsmasq \
  docker \
  docker-buildx \
  docker-compose \
  dust \
  edk2-ovmf \
  evince \
  eza \
  fastfetch \
  fcitx5 \
  fcitx5-gtk \
  fcitx5-qt \
  fd \
  ffmpegthumbnailer \
  fontconfig \
  fzf \
  ghostty \
  git-crypt \
  github-cli \
  gnome-calculator \
  gnome-keyring \
  gnome-themes-extra \
  grim \
  gum \
  gvfs-mtp \
  gvfs-nfs \
  gvfs-smb \
  hypridle \
  hyprland \
  hyprland-guiutils \
  hyprland-preview-share-picker \
  hyprlock \
  hyprpicker \
  hyprsunset \
  imagemagick \
  impala \
  imv \
  inetutils \
  iwd \
  jq \
  kdenlive \
  kvantum-qt5 \
  lazydocker \
  lazygit \
  less \
  libreoffice-fresh \
  libvirt \
  llvm \
  localsend \
  luarocks \
  mako \
  man-db \
  mise \
  mpv \
  nautilus \
  gnome-disk-utility \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nss-mdns \
  nvim \
  obs-studio \
  openbsd-netcat \
  pamixer \
  playerctl \
  plocate \
  polkit-gnome \
  postgresql-libs \
  power-profiles-daemon \
  python-gobject \
  python-poetry-core \
  python-terminaltexteffects \
  qemu-full \
  qt5-wayland \
  ripgrep \
  satty \
  sddm \
  signal-desktop \
  slurp \
  spotify \
  starship \
  stow \
  sushi \
  swaybg \
  swayosd \
  tldr \
  tmux \
  tree-sitter-cli \
  ttf-jetbrains-mono \
  ttf-jetbrains-mono-nerd \
  tzupdate \
  ufw \
  ufw-docker \
  unzip \
  uwsm \
  virt-manager \
  vde2 \
  waybar \
  wayfreeze \
  whois \
  wireless-regdb \
  wiremix \
  wireplumber \
  wl-clipboard \
  woff2-font-awesome \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  xdg-terminal-exec \
  xmlstarlet \
  yaru-icon-theme \
  yay \
  zen-browser-bin \
  zsh

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
